example.property: "I AM IN THE DEFAULT"
server.port: 8090
server.servlet.context-path: /v1/user
spring.jpa.database: "MYSQL"
spring.datasource.platform:  "mysql"
spring.jpa.show-sql: "true"
spring.database.driverClassName: "com.mysql.cj.jdbc.Driver"
spring.datasource.url: "jdbc:mysql://127.0.0.1:3306/java_web?useUnicode=true&characterEncoding=utf-8&serverTimezone=Hongkong"
spring.datasource.username: "root"
spring.datasource.password: "yxt123"
spring.datasource.testWhileIdle: "true"
spring.datasource.validationQuery: "SELECT 1"
spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.MySQL8Dialect"
redis.server: "redis"
redis.port: "6379"
signing.key: "345345fsdfsf5345"
rocketmq.name-server: 127.0.0.1:9876
rocketmq.producer.enable: true
rocketmq.producer.group: user-producer-group
rocketmq.producer.topic: user-producer-topic
rocketmq.consumer.group: user-consumer-group
rocketmq.consumer.topic: user-consumer-topic
