#Setting logging levels
logging:
    level:
      com.netflix: WARN
      org.springframework.web: WARN
      com.thoughtmechanix: DEBUG

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/

zuul:
  ignored-services: '*'
  prefix: /api
  routes:
    organization-service: /organization/**
    licensing-service: /licensing/**

management:
  endpoints:
    web:
      exposure:
        include: routes
