#Setting logging levels
logging:
    level:
      com.netflix: DEBUG
      org.springframework.web: DEBUG
      com.thoughtmechanix: DEBUG

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/

zuul:
  ignored-services: '*'
  prefix: /api
  routes:
    organization-service: /user/**
    licensing-service: /order/**

management:
  endpoints:
    web:
      exposure:
        include: routes

ribbon:
  eureka:
    enabled: false

organization-service:
  ribbon:
    listOfServers: localhost:8091
licensing-service:
  ribbon:
    listOfServers: localhost:8090
