# example
example.property: "I AM IN THE DEFAULT"
# server
server.port: 8091
server.servlet.context-path: /v1/order
# spring
spring.database.driverClassName: "com.mysql.cj.jdbc.Driver"
spring.datasource.master.key: "master"
spring.datasource.master.url: "jdbc:mysql://127.0.0.1:3306/java_web?useUnicode=true&characterEncoding=utf-8&serverTimezone=Hongkong"
spring.datasource.master.username: "root"
spring.datasource.master.password: "yxt123"
spring.datasource.master.platform:  "mysql"
spring.datasource.master.type: "com.alibaba.druid.pool.DruidDataSource"
spring.datasource.master.druid.initial-size: 5
spring.datasource.master.druid.min-idle: 5
spring.datasource.master.druid.max-active: 20
spring.datasource.master.druid.max-wait: 60000
spring.datasource.master.druid.test-while-idle: true
spring.datasource.master.druid.time-between-eviction-runs-millis: 60000
spring.datasource.master.druid.min-evictable-idle-time-millis: 30000
spring.datasource.master.druid.validation-query: SELECT 1
spring.datasource.master.druid.test-on-borrow: false
spring.datasource.master.druid.test-on-return: false
spring.datasource.master.druid.exception-sorter: true
spring.datasource.master.druid.pool-prepared-statements: true
spring.datasource.master.druid.max-pool-prepared-statement-per-connection-size: 20
spring.datasource.master.druid.filters: stat,wall
spring.datasource.master.druid.connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
spring.datasource.master.druid.use-global-data-source-stat: true
spring.datasource.master.druid.stat-view-servlet.login-username: admin
spring.datasource.master.druid.stat-view-servlet.login-password: admin
spring.datasource.slaves[0].key: "slave0"
spring.datasource.slaves[0].url: "jdbc:mysql://127.0.0.1:3306/java_web?useUnicode=true&characterEncoding=utf-8&serverTimezone=Hongkong"
spring.datasource.slaves[0].username: "root"
spring.datasource.slaves[0].password: "yxt123"
spring.datasource.slaves[0].platform:  "mysql"
spring.datasource.slaves[0]: "com.alibaba.druid.pool.DruidDataSource"
spring.datasource.slaves[0].druid.initial-size: 5
spring.datasource.slaves[0].druid.min-idle: 5
spring.datasource.slaves[0].druid.max-active: 20
spring.datasource.slaves[0].druid.max-wait: 60000
spring.datasource.slaves[0].druid.test-while-idle: true
spring.datasource.slaves[0].druid.time-between-eviction-runs-millis: 60000
spring.datasource.slaves[0].druid.min-evictable-idle-time-millis: 30000
spring.datasource.slaves[0].druid.validation-query: SELECT 1
spring.datasource.slaves[0].druid.test-on-borrow: false
spring.datasource.slaves[0].druid.test-on-return: false
spring.datasource.slaves[0].druid.exception-sorter: true
spring.datasource.slaves[0].druid.pool-prepared-statements: true
spring.datasource.slaves[0].druid.max-pool-prepared-statement-per-connection-size: 20
spring.datasource.slaves[0].druid.filters: stat,wall
spring.datasource.slaves[0].druid.connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
spring.datasource.slaves[0].druid.use-global-data-source-stat: true
spring.datasource.slaves[0].druid.stat-view-servlet.login-username: admin
spring.datasource.slaves[0].druid.stat-view-servlet.login-password: admin
spring.datasource.slaves[1].key: "slave1"
spring.datasource.slaves[1].url: "jdbc:mysql://127.0.0.1:3306/java_web?useUnicode=true&characterEncoding=utf-8&serverTimezone=Hongkong"
spring.datasource.slaves[1].username: "root"
spring.datasource.slaves[1].password: "yxt123"
spring.datasource.slaves[1].platform:  "mysql"
spring.datasource.slaves[1].druid.initial-size: 5
spring.datasource.slaves[1].druid.min-idle: 5
spring.datasource.slaves[1].druid.max-active: 20
spring.datasource.slaves[1].druid.max-wait: 60000
spring.datasource.slaves[1].druid.test-while-idle: true
spring.datasource.slaves[1].druid.time-between-eviction-runs-millis: 60000
spring.datasource.slaves[1].druid.min-evictable-idle-time-millis: 30000
spring.datasource.slaves[1].druid.validation-query: SELECT 1
spring.datasource.slaves[1].druid.test-on-borrow: false
spring.datasource.slaves[1].druid.test-on-return: false
spring.datasource.slaves[1].druid.exception-sorter: true
spring.datasource.slaves[1].druid.pool-prepared-statements: true
spring.datasource.slaves[1].druid.max-pool-prepared-statement-per-connection-size: 20
spring.datasource.slaves[1].druid.filters: stat,wall
spring.datasource.slaves[1].druid.connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
spring.datasource.slaves[1].druid.use-global-data-source-stat: true
spring.datasource.slaves[1].druid.stat-view-servlet.login-username: admin
spring.datasource.slaves[1].druid.stat-view-servlet.login-password: admin
# redis
redis.server: "redis"
redis.port: "6379"
# signing
signing.key: "345345fsdfsf5345"
