eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/

mybatis:
  config-location: classpath:mybatis.xml
  mapper-locations: classpath:mybatis/*Mapper.xml

